/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // All semantic colors use CSS variables — they auto-switch with dark/light
        'primary':                   'var(--c-primary)',
        'primary-container':         'var(--c-primary-container)',
        'on-primary':                'var(--c-on-primary)',
        'on-primary-container':      'var(--c-on-primary-container)',
        'secondary':                 'var(--c-secondary)',
        'secondary-container':       'var(--c-secondary-container)',
        'on-secondary':              'var(--c-on-secondary)',
        'on-secondary-container':    'var(--c-on-secondary-container)',
        'tertiary':                  'var(--c-tertiary)',
        'tertiary-container':        'var(--c-tertiary-container)',
        'on-tertiary-container':     'var(--c-on-tertiary-container)',
        'background':                'var(--c-background)',
        'surface':                   'var(--c-surface)',
        'surface-dim':               'var(--c-surface-dim)',
        'surface-container':         'var(--c-surface-container)',
        'surface-container-low':     'var(--c-surface-container-low)',
        'surface-container-high':    'var(--c-surface-container-high)',
        'surface-container-highest': 'var(--c-surface-container-highest)',
        'surface-container-lowest':  'var(--c-surface-container-lowest)',
        'surface-variant':           'var(--c-surface-variant)',
        'surface-bright':            'var(--c-surface-bright)',
        'on-surface':                'var(--c-on-surface)',
        'on-surface-variant':        'var(--c-on-surface-variant)',
        'on-background':             'var(--c-on-background)',
        'outline':                   'var(--c-outline)',
        'outline-variant':           'var(--c-outline-variant)',
        'inverse-surface':           'var(--c-inverse-surface)',
        'inverse-on-surface':        'var(--c-inverse-on-surface)',
        'inverse-primary':           'var(--c-inverse-primary)',
        'error':                     'var(--c-error)',
        'error-container':           'var(--c-error-container)',
        'on-error':                  'var(--c-on-error)',
        'on-error-container':        'var(--c-on-error-container)',
      },
      fontFamily: {
        inter:   ['Inter', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
      },
      fontSize: {
        'h1':         ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2':         ['36px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3':         ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg':    ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':    ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm':    ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1',   letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
