artifact_location: file:C:/Users/Abdurrehman/Desktop/data science project/mlflow_tracking/311132056579872548
creation_time: 1777649926026
experiment_id: '311132056579872548'
last_update_time: 1777649926026
lifecycle_stage: active
name: Student_Performance_Prediction
trace_location: null
workspace: default
